encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins: [ "jemoji" ]
safe: true
lsi: false

##########################
# Slides.
##########################
slides:
  - slides.about
  - slides.project
  - slides.architecture
  - slides.concepts
  - slides.lamp-example
  - slides.industrial-use-case
  - slides.configuration-files
  - slides.tools
  - slides.links

uc.slides:
  - uc.slides.minimal


##########################
# The web site structure.
# Mainly menu names.
##########################

# New locale => translate all the keys.

default-locale: en
locales:
  en:
    icon: gb.png
    language: English
    menu-lang: Language
    menu-project: Project
    menu-users: Users
    menu-developers: Developers
    menu-search: Search
    search: Search...
    s-menu-download: Download
    s-menu-user-guide: User Guide
    s-menu-support: Support
    s-menu-news: News
    s-menu-what-is-roboconf: What is Roboconf?
    s-menu-license: License
    s-menu-roadmap: Roadmap
    s-menu-source-code: Source Code
    s-menu-team: Team
    s-menu-events: Events &amp; Publications
    s-menu-projects: Reference Projects
    s-menu-graphics: Graphics
    s-menu-links: Links
    s-menu-dev-guide: Developer Guide
    s-menu-videos: Videos
    sep: ": "

  fr:
    icon: fr.png
    language: Français
    menu-lang: Langage
    menu-project: Projet
    menu-users: Utilisateurs
    menu-developers: Développeurs
    menu-search: Recherche
    search: Rechercher...
    s-menu-download: Télécharger
    s-menu-user-guide: Guide Utilisateur
    s-menu-support: Support
    s-menu-news: Nouveautés
    s-menu-what-is-roboconf: Roboconf
    s-menu-license: Licence
    s-menu-roadmap: Feuille de Route
    s-menu-source-code: Code Source
    s-menu-team: Équipe
    s-menu-events: Événements &amp; Publications
    s-menu-projects: Projets Références
    s-menu-graphics: Ressources Graphiques
    s-menu-links: Liens
    s-menu-dev-guide: Guide Développeur
    s-menu-videos: Vidéos
    sep: " : "

# Note that user and developer guides data have been externalized under "_data".
  